### ISSUE TITLE
Database query file

### ISSUE THREAD

**Issue by HayaksBird** [HayaksBird/UniHub#1]
Michael, update the database query file, since it has the following issues:
* No "DROP TABLE IF EXISTS" at the beginning. It is tedious to relaunch the database.
* Wrong table order. The table with the foreign key must be created AFTER its dependency table.
In addition, it's redundant to add '_table' at the end of each table name

**Comment by HayaksBird** [comment]
Btw, do we really need the 'university field'? I think it's redundant

**Comment by HayaksBird** [comment]
In addition, why does the review_table have the 'prof_id' and the 'user_id'? I though that we will just place the reviews under the post and that's it. Are we planning to relate them to the user or to the professor somehow?

**Comment by HayaksBird** [comment]
Add some sample data for the API tests

**Comment by HayaksBird** [comment]
Btw, do we really need the 'university field'? I think it's redundant.

Also add some sample data for the API tests.

**Comment by l1ah1m** [comment]
yeah cuz later on we will have more unis, leave it there

**Comment by HayaksBird** [comment]
Got it
